FROM centos:7

ENV container docker

RUN yum install -y openssh-server openssh-clients \
    && yum install -y sudo \
    && yum install -y nano \
    && yum install -y curl \
    && yum install -y wget \
    && yum install git -y \
    && yum -y install initscripts \
    && yum clean all \
    && systemctl enable sshd.service

# Install docker
#RUN curl -fsSL https://get.docker.com/ | sh \
#    && systemctl enable docker

# Install minikube
RUN yum -y install epel-release \
    && yum -y install libvirt qemu-kvm virt-install virt-top libguestfs-tools bridge-utils \
    && systemctl enable libvirtd \
    && sudo usermod -a -G libvirt $(whoami) \
    && wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
    && chmod +x minikube-linux-amd64 \
    && sudo mv minikube-linux-amd64 /usr/local/bin/minikube

# Installing kubectl
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl \
    && chmod +x kubectl \
    && sudo mv kubectl  /usr/local/bin/

EXPOSE 22 80 443 8080 3000

USER root

CMD ["/usr/sbin/init"]


# systemctl start docker
# systemctl start libvirtd
