FROM centos:7

ENV container docker

WORKDIR /home/ec2_user

RUN yum install -y openssh-server openssh-clients \
    && yum install -y sudo \
    && yum install -y nano \
    && yum install -y curl \
    && yum install -y wget \
    && yum install git -y \
    && yum -y install initscripts \
    && yum clean all \
    && systemctl enable sshd.service

RUN ssh-keygen -A \
    && adduser ec2_user \
    && echo "ec2_user:password" | chpasswd

# Install docker
RUN curl -fsSL https://get.docker.com/ | sh \
   && systemctl enable docker

RUN mkdir -p .ssh

ADD authorized_keys .ssh/

USER ec2_user

EXPOSE 22 80 443 8080 3000

ENTRYPOINT [ "/usr/sbin/init" ]
