FROM jrei/systemd-ubuntu:20.04

RUN apt-get update

RUN apt-get install sudo -y \
    && apt-get install git -y \
    && apt-get install nano -y \
    && apt-get install locales -y \
    && apt-get install curl -y \
    && apt-get install openssh-server -y \
    && apt-get install openssh-client -y

# Install Docker
RUN apt-get update \
    && sudo apt-get install -y gnupg2 \
    && sudo apt-get install software-properties-common -y \
    && sudo apt-get install docker.io -y \
    && sudo systemctl enable docker

# Install Kubernetes
RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add \
    && sudo apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main" \
    && sudo apt-get install kubeadm kubelet kubectl -y \
    && sudo apt-mark hold kubeadm kubelet kubectl

# https://stackoverflow.com/questions/52119985/kubeadm-init-shows-kubelet-isnt-running-or-healthy
RUN touch /etc/systemd/system/kubelet.service.d/20-allow-swap.conf \
    && printf '[Service]\nEnvironment="KUBELET_EXTRA_ARGS=--fail-swap-on=false"' >> /etc/systemd/system/kubelet.service.d/20-allow-swap.conf

EXPOSE 22 80 443 8080 3000 5000

USER root

CMD ["/lib/systemd/systemd"]