apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ec2-pod
  template:
    metadata:
      labels:
        app: ec2-pod
    spec:
      containers:
      - name: alpine
        image: congttl/alpine
        ports:
        - containerPort: 22
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ec2-service
spec:
  selector:
    app: ec2-pod
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: ssh
    port: 22
    targetPort: 22
  type: LoadBalancer
